# Generated by Django 5.0.6 on 2026-02-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Metric Type',
                'verbose_name_plural': 'Metric Types',
            },
        ),
        migrations.CreateModel(
            name='MetricReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_readings', to='devices.device')),
                ('metric', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='metrics.metric')),
            ],
            options={
                'verbose_name': 'Metric Reading',
                'verbose_name_plural': 'Metric Readings',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', '-timestamp'], name='metrics_met_device__45790f_idx'), models.Index(fields=['metric', '-timestamp'], name='metrics_met_metric__3dbf3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_thresholds', to='devices.device')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrics.metric')),
            ],
            options={
                'verbose_name': 'Metric Threshold',
                'verbose_name_plural': 'Metric Thresholds',
                'unique_together': {('device', 'metric')},
            },
        ),
    ]
