# Generated by Django 5.2 on 2026-05-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_metricprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricprediction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
