from django.contrib import admin
from .models import Metric, MetricReading, MetricThreshold


@admin.register(Metric)
class MetricAdmin(admin.ModelAdmin):
    """
    Metric Type Admin Interface
    Manages the types of metrics that can be collected (bandwidth, latency, etc.)
    """
    list_display = ('name', 'unit', 'description')
    search_fields = ('name',)
    ordering = ('name',)


@admin.register(MetricReading)
class MetricReadingAdmin(admin.ModelAdmin):
    """
    Metric Reading Admin Interface
    Displays historical metric data collected from devices.
    This is time-series data showing device performance over time.
    """
    list_display = ('device', 'metric', 'value', 'timestamp')
    list_filter = ('device', 'metric', 'timestamp')
    search_fields = ('device__name', 'metric__name')
    readonly_fields = ('device', 'metric', 'value', 'timestamp')
    date_hierarchy = 'timestamp'
    ordering = ('-timestamp',)

    def has_add_permission(self, request):
        # Metric readings are auto-generated by monitoring tasks
        return False

    def has_delete_permission(self, request, obj=None):
        # Readings should not be manually deleted
        return False


@admin.register(MetricThreshold)
class MetricThresholdAdmin(admin.ModelAdmin):
    """
    Metric Threshold Admin Interface
    Manages alert thresholds for device metrics.
    Defines when warnings and critical alerts should be triggered.
    """
    list_display = ('device', 'metric', 'warning_threshold', 'critical_threshold', 'is_active')
    list_filter = ('is_active', 'device', 'metric')
    search_fields = ('device__name', 'metric__name')
    fieldsets = (
        ('Configuration', {
            'fields': ('device', 'metric')
        }),
        ('Thresholds', {
            'fields': ('warning_threshold', 'critical_threshold')
        }),
        ('Status', {
            'fields': ('is_active',)
        }),
    )

