from django.contrib import admin
from .models import MonitoringTask, MonitoringReport, SystemHealth


@admin.register(MonitoringTask)
class MonitoringTaskAdmin(admin.ModelAdmin):
    """
    Monitoring Task Admin Interface
    Manages scheduled monitoring tasks that collect metrics from devices.
    """
    list_display = ('name', 'device', 'assigned_to', 'task_type', 'interval', 'enabled', 'last_run', 'last_status')
    list_filter = ('task_type', 'enabled', 'last_status', 'created_at')
    search_fields = ('name', 'device__name')
    fieldsets = (
        ('Task Information', {
            'fields': ('name', 'description', 'device', 'assigned_to', 'task_type')
        }),
        ('Scheduling', {
            'fields': ('interval', 'timeout', 'enabled')
        }),
        ('Status', {
            'fields': ('last_run', 'last_status'),
            'classes': ('collapse',)
        }),
        ('Timestamps', {
            'fields': ('created_at', 'updated_at'),
            'classes': ('collapse',)
        }),
    )
    readonly_fields = ('created_at', 'updated_at', 'last_run', 'last_status')


@admin.register(MonitoringReport)
class MonitoringReportAdmin(admin.ModelAdmin):
    """
    Monitoring Report Admin Interface
    Displays execution logs and results of monitoring tasks.
    """
    list_display = ('task', 'status', 'duration_ms', 'metrics_collected', 'executed_at')
    list_filter = ('status', 'task', 'executed_at')
    search_fields = ('task__name', 'details')
    readonly_fields = ('task', 'executed_at', 'status', 'duration_ms', 'details', 'metrics_collected')
    fieldsets = (
        ('Task Information', {
            'fields': ('task', 'executed_at')
        }),
        ('Execution Results', {
            'fields': ('status', 'duration_ms', 'metrics_collected')
        }),
        ('Details', {
            'fields': ('details',)
        }),
    )
    date_hierarchy = 'executed_at'
    ordering = ('-executed_at',)

    def has_add_permission(self, request):
        # Reports are auto-generated by monitoring system
        return False

    def has_delete_permission(self, request, obj=None):
        # Keep historical reports
        return False


@admin.register(SystemHealth)
class SystemHealthAdmin(admin.ModelAdmin):
    """
    System Health Admin Interface
    Provides a dashboard view of overall monitoring system health and statistics.
    """
    list_display = ('healthy_devices', 'total_devices', 'total_alerts', 'uptime_percentage', 'last_update')
    readonly_fields = ('healthy_devices', 'total_devices', 'total_alerts', 'failed_tasks', 
                      'total_tasks', 'uptime_percentage', 'last_update')
    fieldsets = (
        ('Device Status', {
            'fields': ('healthy_devices', 'total_devices')
        }),
        ('Alert Status', {
            'fields': ('total_alerts',)
        }),
        ('Task Status', {
            'fields': ('failed_tasks', 'total_tasks')
        }),
        ('System Metrics', {
            'fields': ('uptime_percentage', 'last_update')
        }),
    )

    def has_add_permission(self, request):
        # Only one SystemHealth record should exist
        return not SystemHealth.objects.exists()

    def has_delete_permission(self, request, obj=None):
        return False

