# Generated by Django 5.0.6 on 2026-02-28 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthy_devices', models.IntegerField(default=0)),
                ('total_devices', models.IntegerField(default=0)),
                ('total_alerts', models.IntegerField(default=0)),
                ('failed_tasks', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('uptime_percentage', models.FloatField(default=100.0)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Health',
                'verbose_name_plural': 'System Health',
            },
        ),
        migrations.CreateModel(
            name='MonitoringTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('snmp', 'SNMP Polling'), ('ping', 'ICMP Ping'), ('http', 'HTTP Check'), ('tcp', 'TCP Connection'), ('dns', 'DNS Lookup')], max_length=50)),
                ('interval', models.IntegerField(help_text='Interval in seconds')),
                ('timeout', models.IntegerField(default=5, help_text='Timeout in seconds')),
                ('enabled', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_tasks', to='devices.device')),
            ],
            options={
                'verbose_name': 'Monitoring Task',
                'verbose_name_plural': 'Monitoring Tasks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MonitoringReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], max_length=20)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('metrics_collected', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='monitoring.monitoringtask')),
            ],
            options={
                'verbose_name': 'Monitoring Report',
                'verbose_name_plural': 'Monitoring Reports',
                'ordering': ['-executed_at'],
                'indexes': [models.Index(fields=['task', '-executed_at'], name='monitoring__task_id_9875a0_idx')],
            },
        ),
    ]
