from django.contrib import admin
from .models import AlertRule, Alert, NotificationChannel


@admin.register(AlertRule)
class AlertRuleAdmin(admin.ModelAdmin):
    """
    Alert Rule Admin Interface
    Manages the conditions that trigger alerts.
    """
    list_display = ('name', 'device', 'metric', 'condition', 'threshold', 'severity', 'enabled')
    list_filter = ('severity', 'enabled', 'created_at')
    search_fields = ('name', 'device__name', 'metric__name')
    fieldsets = (
        ('Rule Information', {
            'fields': ('name', 'description')
        }),
        ('Target', {
            'fields': ('device', 'metric')
        }),
        ('Condition', {
            'fields': ('condition', 'threshold')
        }),
        ('Alert Configuration', {
            'fields': ('severity', 'enabled')
        }),
    )


@admin.register(Alert)
class AlertAdmin(admin.ModelAdmin):
    """
    Alert Admin Interface
    Displays alert history and current alert status.
    Users can acknowledge and resolve alerts from this interface.
    """
    list_display = ('device', 'severity', 'status', 'triggered_at', 'acknowledged_by')
    list_filter = ('severity', 'status', 'triggered_at')
    search_fields = ('device__name', 'message')
    readonly_fields = ('rule', 'device', 'triggered_at', 'message')
    fieldsets = (
        ('Alert Information', {
            'fields': ('rule', 'device', 'severity', 'message')
        }),
        ('Status Management', {
            'fields': ('status', 'acknowledged_by')
        }),
        ('Timeline', {
            'fields': ('triggered_at', 'acknowledged_at', 'resolved_at'),
            'classes': ('collapse',)
        }),
    )
    date_hierarchy = 'triggered_at'
    ordering = ('-triggered_at',)

    def has_add_permission(self, request):
        # Alerts are automatically generated by the monitoring system
        return False


@admin.register(NotificationChannel)
class NotificationChannelAdmin(admin.ModelAdmin):
    """
    Notification Channel Admin Interface
    Manages how users receive alert notifications (email, SMS, webhooks, etc.)
    """
    list_display = ('user', 'channel_type', 'address', 'is_active', 'verified')
    list_filter = ('channel_type', 'is_active', 'verified')
    search_fields = ('user__username', 'address')
    fieldsets = (
        ('Channel Information', {
            'fields': ('user', 'channel_type', 'address')
        }),
        ('Status', {
            'fields': ('is_active', 'verified')
        }),
    )

